apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-fmu-sample"
spec:
  stages:
    - name: "production"
      sequences:
        - name: "example-fmu"
          tasks:
            - name: "remote-simulation"